### ISSUE TITLE
Leak child process if execv faild

### ISSUE THREAD

**Issue by dvetutnev** [boostorg/process#151] opened 2020-03-22 19:15 UTC
Test: https://github.com/odant/conan-boost/blob/develop/test_package/test_boost_process_leak_child.cpp
Patch: https://github.com/odant/conan-boost/blob/develop/fix_leak_child_process.patch

**Comment by pogaram** [comment] 2020-06-20 10:20
It seems there is also a pipe leak in this case.

**Comment by arconamagi** [comment] 2022-02-12 16:09
Are there any news on this issue? Was it fixed?

**Comment by martinus** [comment] 2023-01-10 12:51
@klemens-morgenstern is this a duplicate of #265, can this now be closed?

**Comment by klemens-morgenstern** [comment] 2023-01-10 12:57
I think so.

**Closed by klemens-morgenstern** 2023-01-10 12:57 UTC
